const ADD_FILE_REQUEST = 'ADD_FILE_REQUEST';
const ADD_FILE_SUCCESS = 'ADD_FILE_SUCCESS';
const ADD_FILE_ERROR = 'ADD_FILE_ERROR';

const ADD_RDI_REQUEST = 'ADD_RDI_REQUEST';
const ADD_RDI_SUCCESS = 'ADD_RDI_SUCCESS';
const ADD_RDI_ERROR = 'ADD_RDI_ERROR';

module.exports = {
  ADD_FILE_REQUEST, ADD_FILE_SUCCESS, ADD_FILE_ERROR,
  ADD_RDI_REQUEST, ADD_RDI_SUCCESS, ADD_RDI_ERROR
};